services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FUNCTION_MANAGER_URL=http://function-manager:5001
    depends_on:
      - function-manager

  function-manager:
    build:
      context: ./function-manager
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway